name: Deploy mixStore prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: publish
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          dotnet-install.sh -v 8.0.100-preview.6.23330.14
          dotnet publish -c Release

      - name: trans code to the server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          scp: |
            'MixApp/bin/Release/net8.0/publish/wwwroot' => /home/repository/MixApp
