name: Build

on:
  push:
    branches: [ "prod" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shenzhen.aliyuncs.com"
        access-key-id: "${{ secrets.KEY_ID }}"
        access-key-secret: "${{ secrets.SECRET_KEY }}"

    - name: build and publish
      run: bash ./.build.sh

    - name: upload to oss
      run: ossutil cp -rf ./MixApp.Web/bin/Release/net8.0/publish/wwwroot oss://mixstore
