name: Build

on:
  push:
    branches: [ "prod" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build and publish
      run: bash ./.build.sh
      
    - uses: actions/checkout@master
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shenzhen.aliyuncs.com"
        access-key-id: "${{ secrets.KEY_ID }}"
        access-key-secret: "${{ secrets.SECRET_KEY }}"
    - run: ossutil cp -rf MixApp.Shared/bin/Release/net8.0/publish/wwwroot oss://mixstore/
